[package]
name = "healthcheck"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = 'fat'
debug = false
strip = true
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = false

[dependencies]
axum = "0.8.3"
tokio = { version = "1.44.1", features = ["full"] }
