services:
  healthcheck:
    build: .
    ports:
      - "8001:8001"
      - "8002:8002"
    environment:
      - PORT=8001,8002
      - HEALTHCHECK=/health,/check-health
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "/usr/bin/curl", "-f", "http://localhost:8001/health" ]
      interval: 1s
      timeout: 1s
      retries: 3